MD005:
  severity: warning
MD012:
  maximum: 2
  severity: warning
MD013:
  line_length: 240
  heading_line_length: 120
  code_blocks: false
  tables: false
MD022:
  lines_above: 1
  lines_below: 0
MD031: false
MD032: false
MD033: true
MD036: false
MD051:
  ignore_case: true
